default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # database: multiseams_development
test:
  <<: *default
  # database: multiseams_test

production:
  <<: *default
  # database: multiseams_production
  # username: multiseams
  # password: <%= ENV['MULTISEAMS_DATABASE_PASSWORD'] %>